// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArPoJZai4N-8OuIZrBOn4rl-uRmRtqrGY',
    appId: '1:225494246694:web:1230c1e47d4fa0d0a60de7',
    messagingSenderId: '225494246694',
    projectId: 'scroff-app',
    authDomain: 'scroff-app.firebaseapp.com',
    storageBucket: 'scroff-app.firebasestorage.app',
    measurementId: 'G-Q7QQP21L3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsLMrRDg5EVFNDOvbtUP7ePVsLxy5wsFw',
    appId: '1:225494246694:android:5be53785463843f0a60de7',
    messagingSenderId: '225494246694',
    projectId: 'scroff-app',
    storageBucket: 'scroff-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCboo3et0EOibkcs5T362SbCRrwGIVklxk',
    appId: '1:225494246694:ios:f0512140798eb8ada60de7',
    messagingSenderId: '225494246694',
    projectId: 'scroff-app',
    storageBucket: 'scroff-app.firebasestorage.app',
    iosBundleId: 'com.example.scroff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCboo3et0EOibkcs5T362SbCRrwGIVklxk',
    appId: '1:225494246694:ios:f0512140798eb8ada60de7',
    messagingSenderId: '225494246694',
    projectId: 'scroff-app',
    storageBucket: 'scroff-app.firebasestorage.app',
    iosBundleId: 'com.example.scroff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArPoJZai4N-8OuIZrBOn4rl-uRmRtqrGY',
    appId: '1:225494246694:web:dcd996bdbe0bc6f2a60de7',
    messagingSenderId: '225494246694',
    projectId: 'scroff-app',
    authDomain: 'scroff-app.firebaseapp.com',
    storageBucket: 'scroff-app.firebasestorage.app',
    measurementId: 'G-3G92BMQ4B7',
  );
}
